### ISSUE TITLE
Whois Worker

### ISSUE THREAD

**Issue by WesWrench** [mnemonic-no/act-workers#217]
Hello,

To begin, thank you very much for this enormous work.
I wanted to know why is there no feature to do an automated "whois" when handling the IOCs on the graph and thus benefit from the correlations on the whois-registrant-email and whois-registrant-phone .
I looked at the workers' codes, and in fact it is only possible to retrieve this kind of information from the MISP worker. Do you assume that the whois will be done by a worker on the MISP side? I think it would be interesting to be able to investigate dynamically with this kind of feature.

Best regards,

**Comment by frbor** [comment]
Closing this issue.
We know that there are APIs available here, which are rate limited, where you can also pay for a higher rate. I someone else want to look into this we will be happy to review a PR.
